set foreign_key_checks=0;
delete  FROM efdremote.community;
delete  FROM efdremote.country;
delete  FROM efdremote.communityyearnotes;
delete  FROM efdremote.communityyearnotes;
delete  FROM efdremote.images;
delete  FROM efdremote.livelihoodzone;
delete  FROM efdremote.project;
delete  FROM efdremote.projectlz;
delete  FROM efdremote.referencecode;
delete  FROM efdremote.resourcesubtype;
delete  FROM efdremote.resourcetype;
delete  FROM efdremote.site;
delete  FROM efdremote.wealthgroup;
delete  FROM efdremote.wealthgroupinterview;
delete  FROM efdremote.wealthgroupinterview_assetcash;
delete  FROM efdremote.wealthgroupinterview_assetfoodstock;
delete  FROM efdremote.wealthgroupinterview_assetland;
delete  FROM efdremote.wealthgroupinterview_assetlivestock;
delete  FROM efdremote.wealthgroupinterview_assettradeable;
delete  FROM efdremote.wealthgroupinterview_assettree;
delete  FROM efdremote.wealthgroupinterview_crop;
delete  FROM efdremote.wealthgroupinterview_employment;
delete  FROM efdremote.wealthgroupinterview_foodpurchase;
delete  FROM efdremote.wealthgroupinterview_livestockproducts;
delete  FROM efdremote.wealthgroupinterview_livestocksales;
delete  FROM efdremote.wealthgroupinterview_nonfoodpurchase;
delete  FROM efdremote.wealthgroupinterview_transfer;
delete  FROM efdremote.wealthgroupinterview_wildfood;
delete  FROM efdremote.wgcharacteristicsresource;
set foreign_key_checks=1;

